# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: k8sBuild
    steps:
    - task: Docker@2
      displayName: 'Build an image'
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/py/Dockerfile'
        tags: '$(Build.BuildNumber)'

    - task: ECRPushImage@1
      displayName: 'Push on ECR'
      inputs:
        awsCredentials: 'S3 Edilportale'
        regionName: 'eu-south-1'
        sourceImageName: '$(Build.DefinitionName)'
        sourceImageTag: '$(Build.BuildNumber)'
        repositoryName: '$(Build.DefinitionName)'
        pushTag: '$(Build.BuildNumber)'
        autoCreateRepository: true
        removeDockerImage: true
        logRequest: true
        logResponse: true